cout << "ID Product          : ";
            cin >> id;
            cout << "Name Product        : ";
            cin >> nama;
            cout << "Harga Product       : ";
            cin >> harga;
            cout << "Stok Product        : ";
            cin >> stok;
            cout << "Jenis Product       : ";
            cin >> jenis;
            cout << "Bahan Product       : ";
            cin >> bahan;
            cout << "Warna               : ";
            cin >> warna;
            cout << "Size Product        : ";
            cin >> size;
            cout << "Merk Product        : ";
            cin >> merk;